using System.Security.Claims;
using Microsoft.AspNetCore.Antiforgery;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.Extensions.Primitives;
using Xunit;

namespace Auth.Security.Tests;

public class AccountFormSecurityTests
{
    // This suite does not start the Web/API host or connect to a database.
    // Source contracts tie the real framework token checks below to the account
    // endpoints and classic Blazor forms without adding a hosting dependency.
    [Theory]
    [InlineData("login", "Pages/Login.razor")]
    [InlineData("logout", "Shared/TopBar.razor")]
    public void BothAccountFormsPostTokensAndValidateBeforeSideEffects(string action, string component)
    {
        var program = Source("Program.cs");
        var start = program.IndexOf($"app.MapPost(\"/account/{action}\"", StringComparison.Ordinal);
        Assert.True(start >= 0);
        var end = program.IndexOf("\n});", start, StringComparison.Ordinal);
        var endpoint = program[start..end];
        var validation = endpoint.IndexOf("antiforgery.IsRequestValidAsync(http)", StringComparison.Ordinal);
        Assert.True(validation >= 0);
        Assert.Contains("return Results.BadRequest", endpoint);
        Assert.True(validation < endpoint.IndexOf(action == "login" ? "api.LoginAsync" : "sessions.Find", StringComparison.Ordinal));
        Assert.DoesNotContain("DisableAntiforgery", program);
        Assert.DoesNotContain("app.MapGet(\"/account/logout\"", program);

        var markup = Source(component);
        Assert.Contains($"method=\"post\" action=\"/account/{action}\"", markup);
        Assert.Contains("name=\"@AccountFormToken.FormFieldName\" value=\"@AccountFormToken.RequestToken\"", markup);
        Assert.Contains("type=\"submit\"", markup);
        Assert.DoesNotContain("href=\"/account/logout\"", markup);
    }

    [Fact]
    public void SecurityConfigurationIsEnvironmentBasedAndFormsDoNotContainCredentials()
    {
        var program = Source("Program.cs");
        Assert.Contains("options.DetailedErrors = builder.Environment.IsDevelopment()", program);
        Assert.Contains("options.EnableDetailedErrors = builder.Environment.IsDevelopment()", program);
        Assert.Contains("options.Cookie.HttpOnly = true", program);
        Assert.Contains("options.Cookie.SameSite = SameSiteMode.Lax", program);
        Assert.Contains("options.Cookie.SameSite = SameSiteMode.Strict", program);
        Assert.Contains("? CookieSecurePolicy.SameAsRequest : CookieSecurePolicy.Always", program);
        Assert.DoesNotContain("OperatingSystem.IsWindows", program);
        Assert.Contains("AddScoped<AntiforgeryTokenSet>", program);
        Assert.Contains("GetAndStoreTokens(http)", program);
        Assert.Contains("var message = app.Environment.IsDevelopment()", program);
        Assert.DoesNotContain("Uri.EscapeDataString(error", program);
        Assert.DoesNotContain("value=\"SuperAdmin@123\"", Source("Pages/Login.razor"));
    }

    [Theory]
    [InlineData(false, false)]
    [InlineData(false, true)]
    [InlineData(true, false)]
    [InlineData(true, true)]
    public async Task PrerenderAndInteractiveTokensWorkWithTheIssuedCookie(bool authenticated, bool interactive)
    {
        using var services = Services();
        var antiforgery = services.GetRequiredService<IAntiforgery>();
        var user = User(authenticated ? "alice" : null);
        var host = Context(services, user);
        var token = antiforgery.GetAndStoreTokens(host);
        var cookie = Cookie(host);

        if (interactive)
        {
            // A new circuit request carries the host cookie. Reading a token
            // must not write headers (the interactive response may have started).
            var circuit = Context(services, user);
            circuit.Request.Headers.Cookie = cookie;
            token = antiforgery.GetTokens(circuit);
            Assert.Equal(0, circuit.Response.Headers.SetCookie.Count);
        }
        else
        {
            // Scoped form resolution during initial prerender shares the cookie
            // already generated by the host middleware in this same request.
            token = antiforgery.GetTokens(host);
        }

        Assert.True(await antiforgery.IsRequestValidAsync(Post(services, user, cookie, token)));
    }

    [Theory]
    [InlineData("missing-cookie")]
    [InlineData("missing-token")]
    [InlineData("forged-token")]
    [InlineData("other-browser")]
    [InlineData("other-user")]
    [InlineData("anonymous-before-login")]
    public async Task MissingForgedOrMismatchedTokensAreRejected(string scenario)
    {
        using var services = Services();
        var antiforgery = services.GetRequiredService<IAntiforgery>();
        var user = User(scenario == "anonymous-before-login" ? null : "alice");
        var host = Context(services, user);
        var token = antiforgery.GetAndStoreTokens(host);
        var cookie = Cookie(host);
        if (scenario == "other-browser")
        {
            var other = Context(services, user);
            antiforgery.GetAndStoreTokens(other);
            cookie = Cookie(other);
        }
        var post = Post(services, scenario is "other-user" or "anonymous-before-login" ? User("bob") : user,
            scenario == "missing-cookie" ? "" : cookie, token);
        if (scenario is "missing-token" or "forged-token")
            post.Request.Form = new FormCollection(new Dictionary<string, StringValues>
            {
                [token.FormFieldName] = scenario == "missing-token" ? "" : "forged"
            });

        Assert.False(await antiforgery.IsRequestValidAsync(post));
    }

    private static ServiceProvider Services()
    {
        var services = new ServiceCollection();
        services.AddLogging();
        services.AddDataProtection().UseEphemeralDataProtectionProvider();
        services.AddAntiforgery();
        return services.BuildServiceProvider();
    }

    private static ClaimsPrincipal User(string? id) => id == null
        ? new ClaimsPrincipal(new ClaimsIdentity())
        : new ClaimsPrincipal(new ClaimsIdentity(new[] { new Claim(ClaimTypes.NameIdentifier, id) }, "Cookies"));

    private static DefaultHttpContext Context(IServiceProvider services, ClaimsPrincipal user)
    {
        var http = new DefaultHttpContext { RequestServices = services, User = user };
        http.Request.Scheme = "https";
        http.Request.Method = "GET";
        return http;
    }

    private static string Cookie(HttpContext context) => context.Response.Headers.SetCookie.ToString().Split(';')[0];

    private static HttpContext Post(IServiceProvider services, ClaimsPrincipal user, string cookie, AntiforgeryTokenSet token)
    {
        var http = Context(services, user);
        http.Request.Method = "POST";
        http.Request.ContentType = "application/x-www-form-urlencoded";
        http.Request.Headers.Cookie = cookie;
        http.Request.Form = new FormCollection(new Dictionary<string, StringValues> { [token.FormFieldName] = token.RequestToken });
        return http;
    }

    private static string Source(string relative)
    {
        for (var directory = new DirectoryInfo(AppContext.BaseDirectory); directory != null; directory = directory.Parent)
        {
            var path = Path.Combine(directory.FullName, "src", "scada_demo_test.Web", relative);
            if (File.Exists(path)) return File.ReadAllText(path);
        }
        throw new FileNotFoundException($"Web source not found: {relative}");
    }
}
